language: node_js
node_js: "10"
services:
  - docker
cache:
  directories:
    - node_modules
sudo: required
dist: trusty
stages:
  - test
  - build
#matrix:
#  include:
#    - name: "macOS"
#      os: osx
#    - name: "Windows"
#      os: windows
#    - name: "Linux"
#      os: linux
jobs:
  include:
    - stage: "build"        
      name: "build docker image"
      script: docker build -t blocklycraftcreator .
    - stage: "test for linux" 
      os: linux
      script: npm install
      script: npm install --global yarn
      script: quasar build -m electron
    - stage: "test for Windows" 
      os: windows
      script: npm install
      script: npm install --global yarn
      script: quasar build -m electron
    - stage: "test for macOS" 
      os: osx
      script: npm install
      script: npm install --global yarn
      script: quasar build -m electron
