sudo: required
dist: trusty

language: node_js
node_js: "10"
services:
  - docker
matrix:
  include:
    - name: "macOS"
      os: osx

    - name: "Windows"
      os: windows

    - name: "Linux"
      os: linux


cache:
  directories:
    - node_modules

install:
  - npm install
  - npm install --global yarn

script:
  - quasar build -m electron
  - docker build -t blocklycraftcreator .
